export const SYS_MSG = {
  SUCCESS: 'Request completed successfully',
  RETRIEVED: 'Resource retrieved successfully',
  CREATED: 'Resource created successfully',
  UPDATED: 'Resource updated successfully',
  DELETED: 'Resource deleted successfully',
  ACCEPTED: 'Request accepted for asynchronous processing',
  NO_CONTENT: 'Request completed successfully with no response body',
  BAD_REQUEST: 'The request could not be processed because it is invalid',
  UNAUTHORIZED: 'Authentication is required or has failed',
  FORBIDDEN: 'You do not have permission to access this resource',
  NOT_FOUND: 'The requested resource was not found',
  CONFLICT: 'The request conflicts with the current resource state',
  VALIDATION_FAILED: 'Request validation failed',
  INTERNAL_SERVER_ERROR: 'An unexpected server error occurred',
  INVALID_CREDENTIALS: 'The provided email or password is incorrect',
  INVALID_REFRESH_TOKEN:
    'The refresh token is invalid, expired, or cannot be used',
  INVALID_OTP: 'The verification code is invalid or has expired',
  OTP_ATTEMPTS_EXCEEDED: 'Too many verification attempts. Try again later',
  EMAIL_NOT_VERIFIED: 'This user email is not verified',
  OTP_NOT_EXPIRED: 'Your verification code has not expired yet',
  USER_NOT_FOUND: 'No user found with the provided email address',
  INVALID_OAUTH_STATE: 'Invalid Oauth State',
  UNVERIFIED_GOOGLE_ACCOUNT_EMAIL: 'Google account email is not verified',
  MISSING_GOOGLE_PROFILE_INFO:
    'Google account did not provide required profile information',
  CONFLICTING_GOOGLE_ACCOUNT:
    'This email is already linked to a different Google account',
  INVALID_REDIRECT_URL: 'Invalid redirect URL',
  INVALID_REDIRECT_URL_PROTOCOL: 'Invalid redirect URL protocol',
  FORBIDDEN_REDIRECT_URL: 'Redirected URL origin not permitted',
  UNVERIFIED_USER: 'The user email is not verified',
  INVALID_TOKEN: 'The token is invalid',
  SANDBOX_CONNECTION_FAILED:
    'Could not connect to your Sandbox Inverter. Check your access token',
  INVERTER_DEACTIVATED: 'Inverter deactivated successfully',
  INVERTER_ALREADY_INACTIVE: 'This inverter is already deactivated',
  EMPTY_WHATSAPP_MESSAGE: 'Either contentSid or a non-empty body is required',
  WAITLIST_SUCCESS: 'Successfully joined the waitlist',
  WAITLIST_EXISTING: 'You are already registered or on the waitlist',
  GOOGLE_MOBILE_AUTH_FAILED: 'Google authentication failed',
  INVALID_GOOGLE_TOKEN: 'Invalid Google token payload',
  ALERT_NOT_FOUND: 'Alert not found',
  NOT_INVERTER_OWNER: 'User does not own inverter',
  NO_FUEL_TYPE_ENTRY: 'No fuel price entry found for selected type',
  ERROR_UPLOADING_IMAGE: 'Error occured uploading image.',
  UPDATE_IMAGE_ERROR: 'Failed to update image',
} as const;
