name: 'Setup project'
description: 'Checks out code, sets up Node/pnpm, and installs dependencies'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
  pnpm-version:
    description: 'pnpm version to use'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile