export enum AlertType {
  BATTERY_PERCENTAGE = 'BATTERY_PERCENTAGE',
  BATTERY_TEMPERATURE = 'BATTERY_TEMPERATURE',
  ENERGY = 'ENERGY',
  OTHER = 'OTHER',
  POWER = 'POWER',
  SOLAR_GEN = 'SOLAR_GEN',
  INVERTER_FAULT = 'INVERTER_FAULT',
  INVERTER_TEMPERATURE = 'INVERTER_TEMPERATURE',
}
